### ISSUE TITLE
Developing Pagoda Webinar

### ISSUE THREAD

**Issue by LuciaNico** [LuciaNico/bipolarvirtual#1]
We created a new mqd file to draft webinar sildes

**Comment by ddlancs** [comment]
Thanks, Guillermo.

I have some time today to devote to the project, so I'll take a look.

DD.

From: Guillermo Perez Algorta ***@***.***>
Sent: 30 October 2024 10:33
To: LuciaNico/bipolarvirtual ***@***.***>
Cc: Dinham, David (Postgraduate Researcher) ***@***.***>; Assign ***@***.***>
Subject: [External] Re: [LuciaNico/bipolarvirtual] Developing Pagoda Webinar (Issue #1)


This email originated outside the University. Check before clicking links or attachments.

Assigned #1<https://github.com/LuciaNico/bipolarvirtual/issues/1> to @ddlancs<https://github.com/ddlancs>.

-

**Comment by LuciaNico** [comment]
@ddlancs I have seen your blog contribution on advance statements. Very cool! Curious about your experience navigating RStudio!
